# Generated by Django 4.2.23 on 2025-07-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_userprofile_role_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='roles',
        ),
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(related_name='modules', to='patient.module'),
        ),
    ]
