# Generated by Django 4.2.23 on 2025-07-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_module_roles_role_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_delete_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_patient',
            field=models.BooleanField(default=True),
        ),
    ]
