# Generated by Django 4.2.23 on 2025-07-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_role_can_delete_patient_role_can_edit_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='can_edit_patient',
            new_name='can_edit',
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_report', models.BooleanField(default=True)),
                ('delete_report', models.BooleanField(default=False)),
                ('edit_report', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.role')),
            ],
        ),
    ]
