# Generated by Django 4.2.23 on 2025-07-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_rename_can_edit_patient_role_can_edit_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
