# Generated by Django 4.2.23 on 2025-07-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_remove_appointment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default=1, upload_to='doctors/'),
            preserve_default=False,
        ),
    ]
