# Generated by Django 4.2.23 on 2025-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='image',
            field=models.ImageField(default=1, upload_to='medical_records/'),
            preserve_default=False,
        ),
    ]
