# Generated by Django 4.2.23 on 2025-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_medicalrecord_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='image',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='medical_records/'),
        ),
    ]
